server:
  error:
    include-binding-errors: always
    include-stacktrace: never
    include-message: always
  port: 8080
  servlet:
    context-path: /apoDB/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apodb
    username: root
    password: Pass.4150
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
